routes/web.php
<?php


Auth::routes();

Route::get('/show-one-entry/{entry}','EntriesController@showOneEntryDisplayView'); // should be available for unsigned users, currently unused



//Route::get('/testing', 'ApiController@api_get_current_tour');


// Under the line routes are not checked
// -----------------------









Route::get('change-password', 'UserController@getChangePassword')->name('user-change-password-get');
Route::post('change-password', 'UserController@postChangePassword')->name('user-change-password-post');



Route::get('/develop', function(){
    return view('admin_panel_view.events.entries_vue');
});



Route::get('/ball-journal-vue', 'BallJournalController@indexVue');





Route::post('change-operator', 'UserController@postChangeOperator')->name('user.change-operator');
Route::get('/matrica', 'MatrixController@getAccessToken1');
Route::get('/cache-token', 'MatrixController@cacheTokenState')->name('cache-token');






Route::group(['middleware' => ['auth', 'change-password']], function () {

    Route::get('/', 'IndexController@index')->name('index');

    Route::group(['middleware' => 'access.ball-journal', 'prefix' => 'ball-journal', 'as' => 'ball-journal.'], function () {
        Route::get('/technician-instruction', 'BallJournalController@showTechnicianInstruction');
        Route::post('/get-one-entry-json-format', 'BallJournalController@getOneEntryJsonFormat');
        Route::post('/', 'BallJournalController@ballSetChangeStore')->name('ball-set-change-store');
        Route::post('/ball-change-store', 'BallJournalController@ballChangeStore')->name('ball-change-store');
        Route::post('/tech-message-store', 'BallJournalController@technicalMessageStore')->name('technical-message-store');
        Route::post('/ball-set-status-change-store', 'BallJournalController@ballSetStatusChangeStore')->name('ball-set-status-change-store');
        Route::post('/ball-set-shuffle-store', 'BallJournalController@ballSetShuffleStore')->name('ball-set-shuffle-store');
        Route::post('/remove-announcement-status/{id}', 'BallJournalController@removeAnnouncementStatus')->name('remove-announcement-status');
        Route::post('/event-complete-form/{id}', 'BallJournalController@completeEventForBallSetChange')->name('ball-set-change-complete');
        Route::get('/{typeId?}', 'BallJournalController@index')->name('index'); // this one should be last on a row
    });



    Route::group(['middleware' => 'access.studio', 'prefix' => 'studio/{studioName}'], function () {
        Route::get('/', 'EntriesController@filter')->name('studio.filter');
        Route::post('/store', 'EntriesController@store')->name('entry.store');
        Route::patch('/update', 'EntriesController@update')->name('entry.update');
        Route::post('/unalert-entry/{entrie}', 'EntriesController@unalertEntry')->name('entry.unalert-entry');
    });



    // admin_panel area routes
    Route::group(['middleware' => 'access.admin_panel_access', 'prefix' => 'admin-panel', 'as' => 'admin-panel.'], function () {

        Route::get('/studios', 'StudioController@index')->name('studios.index');

        Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
            Route::get('/', 'UsersController@users')->name('admin.user.index'); // :todo this one cannot work
//            Route::post('/store', 'EntriesController@store')->name('entry.store');
//            Route::patch('/update', 'EntriesController@update')->name('entry.update');
//            Route::post('/unalert-entry/{id}', 'EntriesController@unalertEntry')->name('entry.unalert-entry');
        });




        Route::get('/entries/{studio}', 'EntriesController@showInBackend')->name('show-entries-in-backend');


        Route::group(['prefix' => 'matrix', 'as' => 'matrix.'], function () {
            Route::get('/', 'MatrixController@index')->name('index');
            Route::post('login', 'MatrixController@login')->name('login');
            Route::post('save', 'MatrixController@saveRoom')->name('save');
            Route::post('signin', 'MatrixController@store')->name('signin');
            Route::delete('delete', 'MatrixController@destroy')->name('delete');
        });


        Route::get('/email', 'EmailController@index')->name('email-index');
        Route::post('/email', 'EmailController@store');
        Route::patch('/email/{id}', 'EmailController@update');
        Route::delete('/email/{id}', 'EmailController@destroy');
        Route::post('/send-mail', 'EmailController@send');




        /*Event Description Types*/
        Route::get('/event-descriptions-types', 'DescriptionsTypeController@index')->name('event-descriptions-types.index');
        Route::post('/event-descriptions-types', 'DescriptionsTypeController@store')->name('event-descriptions-types.store');
        Route::patch('/event-descriptions-types', 'DescriptionsTypeController@update')->name('event-descriptions-types.update');
        Route::delete('/event-descriptions-types', 'DescriptionsTypeController@destroy')->name('event-descriptions-types.destroy');

        Route::get('/event-description-type-mailing-settings', 'DescriptionsTypeController@mailingSettings')->name('event-description-type-mailing-settings');
        Route::patch('/entry-description-type-mailing-settings-update', 'DescriptionsTypeController@mailingSettingsUpdate')->name('event-description-type-mailing-settings-update');
        /*Event Description Types -- END*/




        Route::resource('description', 'DescriptionController'); // all routes related to description
//make sure that this one not needed to be refactored, and just then remove red mark



        /* Information text */
        Route::get('/information/instruction', 'InformationController@instruction')->name('information.instruction');
        Route::get('/information/notification', 'InformationController@notification')->name('information.notification');
        Route::get('/information/notice', 'InformationController@notice')->name('information.notice');

        Route::patch('/information/instruction', 'InformationController@updateInstruction')->name('information.instruction');
        Route::patch('/information/notification', 'InformationController@updateNotification')->name('information.notification');
        Route::patch('/information/notice', 'InformationController@updateNotice')->name('information.notice');
        /* Information text -- END*/



        Route::resource('tech-support-msg', 'TechMsgController');
        Route::resource('chef', 'ChefController');
        Route::resource('operator', 'OperatorController');
        Route::resource('ball-technician', 'BallTechnicianController');
        Route::resource('admin', 'AdminController');
        Route::resource('user', 'UserController'); //todo: not sure that there is some standard methods


        Route::get('/access-structure/abilities', 'StaffAccessStructure\AbilityController@abilities')->name('access-structure.abilities');
        Route::get('/access-structure/assigned-roles', 'StaffAccessStructure\AssignedRoleController@assignedRoles')->name('access-structure.assigned-roles');
        Route::get('/access-structure/permissions', 'StaffAccessStructure\PermissionController@permissions')->name('access-structure.permissions');
        Route::get('/access-structure/roles', 'StaffAccessStructure\RoleController@roles')->name('access-structure.roles');



//        Route::get('/matrix', 'MatrixController@index')->name('matrix-index');

    });











//consider to place all this route to admin-panel prefix, after you refactor them
//    similar routes have they representations undex matrix prefix, deal with them, which one of them are actual

    Route::post('/user/save-operator-to-session', 'OperatorController@saveOperatorToSession');
    // Not used routes------------------------------------------------------------------------------------
    Route::get('/user/{user}', 'UserController@showUserProfile');

    Route::get('matrix/grab-messages', 'MatrixController@getStudioMessagesFromMatrixChat');
    Route::get('matrix/send-message', 'MatrixController@sendMessageToChat');

    Route::post('matrix/chat', 'MatrixController@sendMessageToChat')->name('matrix.chat.send');
    Route::get('matrix/ajax', 'MatrixController@talkToAjax');
    Route::get('matrix/get-messages', 'MatrixController@getMessages');

    Route::get('/admin_panel/matrix', 'MatrixController@index');
    //@todo: consider to remove
    Route::post('matrix/send', 'MatrixController@sendMessage')->name('matrix.send'); //journal.blade.php dependant route. Called when tech.sup. msg. send






    Route::get('/text/tech-instruction', 'InformationController@techInstruction');



});

resources/views/ball_journal_view/partials/entry_table.blade.php
<section class="event_table">
    <table class="table table-sm table-striped">
        <thead>
        <tr>
            <th class="pl-3" scope="col">Дата</th>
            <th scope="col">Время</th>
            <th scope="col">Техник по шарам</th>
            <th scope="col">Тип события</th>
            <th scope="col">Студия</th>
            <th scope="col">№ комплекта</th>
            <th scope="col">№ шара</th>
            <th scope="col">Причина замены шара</th>
            <th scope="col">Статус комплекта <i class="fas fa-info-circle" title="Если статус копплекта установлен на 0, то комплект не используем!!!"></i></th>
            <th scope="col">Примечание</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>

        @foreach($allEntries as $entry)
            <tr title="ID: {{$entry->id}}. @if($entry->binded_edited_entry_id != null){{" Это измененная запись, ID её обновленной версии: ".$entry->binded_edited_entry_id }} @endif " class="@if($entry->entry_completion_status === 0){{"bg-warning"}} @endif @if($entry->binded_edited_entry_id != null){{"bg-secondary"}} @endif">

                <td class="pl-3" scope="row">{{ isset($entry->date) ? $entry->date : '-' }}</td>
                <td class="pl-3">{{ isset($entry->time) ? $entry->time : '-' }} </td>
                <td class="pl-3">{{ isset($entry->user) ? $entry->user->name : '-'}}  </td>
                <td class="pl-3">{{ isset($entry->type->name_ru) ? $entry->type->name_ru : '-' }}</td>
                <td class="pl-3">{{ isset($entry->studio->name_ru) ? $entry->studio->name_ru : '-' }}  </td>
                <td class="pl-3">{{ isset($entry->ball_set_number) ? $entry->ball_set_number : '-' }}</td>
                <td class="pl-3">{{ isset($entry->ball_number) ? $entry->ball_number : '-' }}</td>
                <td class="pl-3">{{ isset($entry->ballCondition->name_ru) ? $entry->ballCondition->name_ru : '-' }}  </td>
                <td class="pl-3">{{ isset($entry->ball_set_status) ? $entry->ball_set_status : '-' }}</td>

                <td class="pl-3 table-description">{{$entry->description}}</td>
                <td class="">@if($entry->entry_completion_status === 0)<a  href='{{ route('ball-journal.index', $entry->id ) }}' type='button' class='btn btn-outline-light text-info btn-sm event-complete-button'>Завершить</a>@endif</td>
                <td class="">
                    <?php
                        if(Auth::check()) {
                            $user = Auth::user();
                            if ($user->isAn('ball-technician')) {
                    ?>
                            <button data-entry-type="{{$entry->type->name_eng}}" data-entry-id="{{$entry->id}}" type='button' class='btn btn-outline-light text-info btn-sm event-edit-button'>Edit</button></td>

                <?php }} ?>


            </tr>

        @endforeach


        </tbody>

    </table>

        @if(!count($allEntries))
            <p class="alert alert-primary mt-5">Данных с такими критериями не существует, попробуйте еще раз! </p>
        @endif


</section>

@if(method_exists($allEntries, 'appends' ))
    {{ $allEntries->appends(Request::except('page'))->links() }}
@endif

resources/views/ball_journal_view/partials/form_views_for_editing_entry.blade.php
    <section class="edit-entry-section">


        <article class="container hidden-container ball-set-planned-change-edit-modal mb-5" data-view-type="planed-ball-set-edit">
            <div  class="container">
                <h4>Плановая замена комплекта шаров - Исправление</h4>
                <hr>
                <form action="{{route('ball-journal.ball-set-change-store')}}" method="post">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="plannedBallSetChangeDateEdit">Дата</label>
                        <input type="date" class="form-control form-date" name="date" id="plannedBallSetChangeDateEdit" >
                    </div>
                    <div class="form-group">
                        <label for="plannedBallSetChangeTimeEdit">Время</label>
                        <input type="time" class="form-control" name="time" id="plannedBallSetChangeTimeEdit">
                    </div>
                    <div class="form-group">
                        <label  class="form-control-label" for="plannedBallSetChangeStudioNameEdit">Студия</label>
                        <select class="form-control" name="studio_id" id="plannedBallSetChangeStudioNameEdit">
                           @foreach($allStudios as $studio)
                                <option value="{{$studio->id}}">{{$studio->name_ru}}</option>
                           @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="plannedBallSetChangeNumberEdit">Номер комплекта шаров</label>
                        <input type="number" class="form-control" name="ball_set_number" id="plannedBallSetChangeNumberEdit">
                    </div>
                    <input type="hidden" name="event_type_id" value="1">
                    <input type="hidden" class="planned-ball-set-change-edit-entry_id" name="entry_id" value="">
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </form>
            </div>
        </article>



        <article class="container hidden-container ball-set-unplanned-change-edit-modal mb-5" data-view-type="unplaned-ball-set-edit">
            <div  class="container">
                <h4>Внеплановая замена комплекта шаров - Исправление</h4>
                <hr>
                <form action="{{route('ball-journal.ball-set-change-store')}}" method="post">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="unplannedBallSetChangeDateEdit">Дата</label>
                        <input type="date" class="form-control form-date" name="date" id="unplannedBallSetChangeDateEdit">
                    </div>
                    <div class="form-group">
                        <label for="unplannedBallSetChangeTimeEdit">Время</label>
                        <input type="time" class="form-control" name="time" id="unplannedBallSetChangeTimeEdit">
                    </div>
                    <div class="form-group">
                        <label  class="form-control-label" for="unplannedBallSetChangeStudioNameEdit">Студия</label>
                        <select class="form-control" name="studio_id" id="unplannedBallSetChangeStudioNameEdit">
                            @foreach($allStudios as $studio)
                                <option value="{{$studio->id}}">{{$studio->name_ru}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="unplannedBallSetChangeNumberEdit">Номер комплекта шаров</label>
                        <input type="number" class="form-control" name="ball_set_number" id="unplannedBallSetChangeNumberEdit">
                    </div>
                    <div class="form-group">
                        <label for="unplannedBallSetChangeDescriptionEdit">Причина замены</label>
                        <textarea  name="description" class="form-control" id="unplannedBallSetChangeDescriptionEdit" placeholder="Введите текст" rows="3"></textarea>
                    </div>
                    <input type="hidden" name="event_type_id" value="2">
                    <input type="hidden" class="unplanned-ball-set-change-edit-entry_id" name="entry_id" value="">

                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </form>
            </div>
        </article>




        <article class="container hidden-container ball-change-event-modal mb-5" data-view-type="ball-edit">
            <div  class="container">
                <h4>Замена шара - Исправление</h4>
                <hr>
                <form action="{{route('ball-journal.ball-change-store')}}" method="post">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label  class="form-control-label" for="ballChangeStudioNameEdit">Студия</label>
                        <select class="form-control" name="studio_id" id="ballChangeStudioNameEdit">
                            @foreach($allStudios as $studio)
                                <option value="{{$studio->id}}">{{$studio->name_ru}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="ballChangeBallSetNumberEdit">Номер комплекта шаров</label>
                        <input type="text" class="form-control" name="ball_set_number" id="ballChangeBallSetNumberEdit">
                    </div>
                    <div class="form-group">
                        <label for="ballChangeBallNumberEdit">Номер шара</label>
                        <input type="text" class="form-control" name="ball_number" id="ballChangeBallNumberEdit" >
                    </div>
                    <div class="form-group">
                        <label for="ballChangeBallChangeReasonEdit">Причину замены шара</label>
                        <select class="form-control" name="ball_change_reason" id="ballChangeBallChangeReasonEdit">
                            @foreach($allBallConditions as $conditions)
                                <option value="{{$conditions->id}}">{{$conditions->name_ru}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <small class="form-text text-muted">Время и дата будут установлены автоматически</small>
                    </div>
                    <input type="hidden" name="event_type_id" value="3">
                    <input type="hidden" class="ball-change-edit-entry_id" name="entry_id" value="">
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </form>
            </div>
        </article>



        <article class="container hidden-container simple-text-event-edit-modal mb-5" data-view-type="technical-message-edit">
            <div  class="container">
                <h4>Техническое сообщение - Исправление</h4>
                <hr>
                <form action="{{route('ball-journal.technical-message-store')}}" method="post">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="technicalMessageDescriptionEdit">Текст сообщения</label>
                        <textarea  name="description" class="form-control" id="technicalMessageDescriptionEdit" placeholder="Введите текст" rows="3"></textarea>
                    </div>
                    <div class="form-group">
                        <input type="hidden" name="announcement" value="0">
                        <input type="checkbox" value="1" name="announcement" class="form-check-input" id="technicalMessageAnnouncementEdit">
                        <label class="form-check-label" for="technicalMessageAnnouncementEdit">Сделать сообщение объявлением</label>
                    </div>
                    <div class="form-group">
                        <small class="form-text text-muted">Время и дата будут установлены автоматически</small>
                    </div>
                    <input type="hidden" name="event_type_id" value="4">
                    <input type="hidden" class="technical-message-edit-entry_id" name="entry_id" value="">
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </form>
            </div>
        </article>



    </section>

resources/views/ball_journal_view/partials/modal_with_event_types.blade.php
    <section class="container text-center main-top-section mb-5 choose-event-type-modal-box mb-5">


        <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Типы событий</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="btn-group-vertical event-type-btn-group container-fluid" role="group" aria-label="Choose event type buttons group">
                            <button type="button" data-view-type="planed-ball-set" class="btn btn-secondary border-bottom-4 border-white">Плановая замена комплекта шаров</button>
                            <button type="button" data-view-type="unplaned-ball-set" class="btn btn-secondary border-bottom-4 border-white">Внеплановая замена комплекта шаров</button>
                            <button type="button" data-view-type="ball" class="btn btn-secondary border-bottom-4 border-white">Замена шара</button>
                            <button type="button" data-view-type="technical-message" class="btn btn-secondary border-bottom-4 border-white">Техническое сообщение</button>
                            <button type="button" data-view-type="ball-set-status" class="btn btn-secondary border-bottom-4 border-white">Присвоить статус комплекту</button>
                            <button type="button" data-view-type="ball-set-shuffle" class="btn btn-secondary border-bottom-4 border-white">Шафл комплектов шаров</button>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <br>
                    </div>
                </div>
            </div>
        </div>

    </section>

resources/views/ball_journal_view/partials/navbar.blade.php
<section class="mb-5">
        <ul class="nav nav-tabs justify-content-center">

            <li class="nav-item "><div class="dropdown">
                    <a class="btn dropdown-toggle"  type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        @if (Auth::user()){{ Auth::user()->username }}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        @can('access-admin-panel')
                            <li><a class="dropdown-item" href="{{ route('admin-panel.studios.index') }}">Панель администрирования</a></li>
                        @endcan

                        <li><a class="dropdown-item" href="{{ url('/logout') }}"
                               onclick="event.preventDefault();
                   document.getElementById('logout-form').submit();">
                                Выйти
                            </a>
                            <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                                <input type="hidden" name="ball_techninian" value="1">
                            </form>
                        </li>
                    </ul>
                    @else
                        <span>Войти</span>
                        <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <li><a href="{{ url('/login') }}">Войти</a></li>
                        </ul>

                    @endif
                </div></li>
            <li class="nav-item"><a  class="nav-link" href="/ball-journal">Главная страница</a></li>
            <li class="nav-item"><a  class="nav-link" href="/ball-journal/technician-instruction">Техническая инструкция</a></li>
        </ul>
    </section>

resources/views/ball_journal_view/partials/new_entry_btn_and_announcements.blade.php
<!-- Button trigger modal -->
<section class="container row">

    <section class="col-4">
        <button type="button" style="background-color:#fff;" class="btn btn-light mb-5 border border-5 border-secondary" data-toggle="modal" data-target=".bd-example-modal-lg">
            <span class="text-black" >Выбрать тип события</span>
        </button>
    </section>

    <section class="announcements-section col-8  @if(isset($ballJournalEntry)) {{'d-none'}}@endif">
        <div class="list-group-item list-group-item-action announcements-wrapper">

                <div href="#" class="list-group-item list-group-item-action flex-column align-items-start active ">
                    <div  class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">Объявления</h5>
                        <button type="button" id="showAllAnnouncementsBtn" class="btn btn-primary mb-2">Показать все объявления</button>

                    </div>
                </div>

            @foreach($allAnnouncements as $announcement)

            <div href="#" class="d-none list-group-item list-group-item-action flex-column align-items-start div-announcement-elements">
                <div class="d-flex w-100 justify-content-between">
                    <small class="text-muted">{{$announcement->created_at->diffForHumans()}}<form class="d-inline ml-2" action="{{route('ball-journal.remove-announcement-status', $announcement->id )}}" method="post"><button type="submit"  class="btn d-none btn-outline-light text-info btn-sm mb-2 delete-notification-btn">Удалить</button></form></small>
                </div>
                <p class="mb-1">{{$announcement->description}}</p>
            </div>

            @endforeach

        </div>
    </section>

</section>

resources/views/ball_journal_view/partials/table_entry_filtering_area.blade.php
<section class="main-bottom-section">


    <nav class="navbar navbar-dark bg-dark ">
        <?php
        if(Auth::check()) {
            $user = Auth::user();
            if ($user->isAn('ball-technician-admin')) {
        ?>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarText">
            <span class="navbar-text text-white">Фильтрация записей</span>
            <hr>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link entry-filter-ball-set-number" href="">По номеру комплекта</a>
                    <form class="form-inline d-none entry-filter-ball-set-number-container">
                        <div class="form-group mx-sm-3 mb-2">
                            <input type="number" class="form-control entry-filter-ball-set-number-submit-input" placeholder="Номер комплекта">
                        </div>
                        <a type="submit" href="ball-journal?entry_filter_ball_set_number" class="btn btn-primary entry-filter-ball-set-number-submit-button mb-2">Отфильтровать</a>
                    </form>
                </li>
                <li class="nav-item">
                    <a class="nav-link entry-filter-event-type" href="#">По типу событий</a>
                    <form class="form-inline d-none entry-filter-event-type-container">
                        <div class="form-group mx-sm-3 mb-2">
                            <select class="form-control entry-filter-event-type-submit-select" name="event_type[]" id="studio-name" multiple>
                                @foreach($eventTypes as $eventType)
                                    <option value="{{$eventType->id}}">{{$eventType->name_ru}}</option>
                                @endforeach
                            </select>
                        </div>
                        <a type="submit" href="ball-journal?entry_filter_event_type" class="btn btn-primary entry-filter-event-type-submit-button mb-2">Отфильтровать</a>
                    </form>
                </li>
                <li class="nav-item">
                    <a class="nav-link entry-filter-time-interval" href="#">По временному интервалу</a>
                    <form class="form-inline d-none entry-filter-time-interval-container">
                        <div class="form-group mx-sm-3 mb-2">
                            <label class="text-white mr-2" for="filterDateStart">От: </label>
                            <input type="date" id="filterDateStart" class="form-control entry-filter-time-interval-start-input" placeholder="Номер комплекта">
                        </div>
                        <div class="form-group mx-sm-3 mb-2">
                            <label class="text-white mr-2" for="filterDateEnd">До: </label>
                            <input type="date" id="filterDateEnd" class="form-control entry-filter-time-interval-end-input" placeholder="Номер комплекта">
                        </div>
                        <a type="submit" href="ball-journal?entry_filter_time_interval" class="btn btn-primary entry-filter-time-interval-submit-button mb-2">Отфильтровать</a>
                    </form>
                </li>
                <li class="nav-item">
                    <a class="nav-link entry-filter-studio" href="#">По студии</a>
                    <form class="form-inline d-none entry-filter-studio-container">
                        <div class="form-group mx-sm-3 mb-2">
                            <select class="form-control entry-filter-studio-submit-select" name="studio-id" id="studio-name">
                                @foreach($allStudios as $studio)
                                    <option value="{{$studio->id}}">{{$studio->name_ru}}</option>
                                @endforeach
                            </select>
                        </div>
                        <a type="submit" href="ball-journal?entry_filter_studio" class="btn btn-primary entry-filter-studio-submit-button mb-2">Отфильтровать</a>
                    </form>
                </li>
                <li class="nav-item">
                    <a type="submit" href="/ball-journal" class="btn btn-primary entry-filter-studio-submit-button mb-2">Показать все записи</a>
                </li>
            </ul>

        </div>
        <?php }} ?>
    </nav>
</section>