routes/web.php
<?php


Auth::routes();

Route::get('/show-one-entry/{entry}','EntriesController@showOneEntryDisplayView'); // should be available for unsigned users, currently unused



//Route::get('/testing', 'ApiController@api_get_current_tour');


// Under the line routes are not checked
// -----------------------









Route::get('change-password', 'UserController@getChangePassword')->name('user-change-password-get');
Route::post('change-password', 'UserController@postChangePassword')->name('user-change-password-post');



Route::get('/develop', function(){
    return view('admin_panel_view.events.entries_vue');
});



Route::get('/ball-journal-vue', 'BallJournalController@indexVue');





Route::post('change-operator', 'UserController@postChangeOperator')->name('user.change-operator');
Route::get('/matrica', 'MatrixController@getAccessToken1');
Route::get('/cache-token', 'MatrixController@cacheTokenState')->name('cache-token');






Route::group(['middleware' => ['auth', 'change-password']], function () {

    Route::get('/', 'IndexController@index')->name('index');

    Route::group(['middleware' => 'access.ball-journal', 'prefix' => 'ball-journal', 'as' => 'ball-journal.'], function () {
        Route::get('/technician-instruction', 'BallJournalController@showTechnicianInstruction');
        Route::post('/get-one-entry-json-format', 'BallJournalController@getOneEntryJsonFormat');
        Route::post('/', 'BallJournalController@ballSetChangeStore')->name('ball-set-change-store');
        Route::post('/ball-change-store', 'BallJournalController@ballChangeStore')->name('ball-change-store');
        Route::post('/tech-message-store', 'BallJournalController@technicalMessageStore')->name('technical-message-store');
        Route::post('/ball-set-status-change-store', 'BallJournalController@ballSetStatusChangeStore')->name('ball-set-status-change-store');
        Route::post('/ball-set-shuffle-store', 'BallJournalController@ballSetShuffleStore')->name('ball-set-shuffle-store');
        Route::post('/remove-announcement-status/{id}', 'BallJournalController@removeAnnouncementStatus')->name('remove-announcement-status');
        Route::post('/event-complete-form/{id}', 'BallJournalController@completeEventForBallSetChange')->name('ball-set-change-complete');
        Route::get('/{typeId?}', 'BallJournalController@index')->name('index'); // this one should be last on a row
    });



    Route::group(['middleware' => 'access.studio', 'prefix' => 'studio/{studioName}'], function () {
        Route::get('/', 'EntriesController@filter')->name('studio.filter');
        Route::post('/store', 'EntriesController@store')->name('entry.store');
        Route::patch('/update', 'EntriesController@update')->name('entry.update');
        Route::post('/unalert-entry/{entrie}', 'EntriesController@unalertEntry')->name('entry.unalert-entry');
    });



    // admin_panel area routes
    Route::group(['middleware' => 'access.admin_panel_access', 'prefix' => 'admin-panel', 'as' => 'admin-panel.'], function () {

        Route::get('/studios', 'StudioController@index')->name('studios.index');

        Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
            Route::get('/', 'UsersController@users')->name('admin.user.index'); // :todo this one cannot work
//            Route::post('/store', 'EntriesController@store')->name('entry.store');
//            Route::patch('/update', 'EntriesController@update')->name('entry.update');
//            Route::post('/unalert-entry/{id}', 'EntriesController@unalertEntry')->name('entry.unalert-entry');
        });




        Route::get('/entries/{studio}', 'EntriesController@showInBackend')->name('show-entries-in-backend');


        Route::group(['prefix' => 'matrix', 'as' => 'matrix.'], function () {
            Route::get('/', 'MatrixController@index')->name('index');
            Route::post('login', 'MatrixController@login')->name('login');
            Route::post('save', 'MatrixController@saveRoom')->name('save');
            Route::post('signin', 'MatrixController@store')->name('signin');
            Route::delete('delete', 'MatrixController@destroy')->name('delete');
        });


        Route::get('/email', 'EmailController@index')->name('email-index');
        Route::post('/email', 'EmailController@store');
        Route::patch('/email/{id}', 'EmailController@update');
        Route::delete('/email/{id}', 'EmailController@destroy');
        Route::post('/send-mail', 'EmailController@send');




        /*Event Description Types*/
        Route::get('/event-descriptions-types', 'DescriptionsTypeController@index')->name('event-descriptions-types.index');
        Route::post('/event-descriptions-types', 'DescriptionsTypeController@store')->name('event-descriptions-types.store');
        Route::patch('/event-descriptions-types', 'DescriptionsTypeController@update')->name('event-descriptions-types.update');
        Route::delete('/event-descriptions-types', 'DescriptionsTypeController@destroy')->name('event-descriptions-types.destroy');

        Route::get('/event-description-type-mailing-settings', 'DescriptionsTypeController@mailingSettings')->name('event-description-type-mailing-settings');
        Route::patch('/entry-description-type-mailing-settings-update', 'DescriptionsTypeController@mailingSettingsUpdate')->name('event-description-type-mailing-settings-update');
        /*Event Description Types -- END*/




        Route::resource('description', 'DescriptionController'); // all routes related to description
//make sure that this one not needed to be refactored, and just then remove red mark



        /* Information text */
        Route::get('/information/instruction', 'InformationController@instruction')->name('information.instruction');
        Route::get('/information/notification', 'InformationController@notification')->name('information.notification');
        Route::get('/information/notice', 'InformationController@notice')->name('information.notice');

        Route::patch('/information/instruction', 'InformationController@updateInstruction')->name('information.instruction');
        Route::patch('/information/notification', 'InformationController@updateNotification')->name('information.notification');
        Route::patch('/information/notice', 'InformationController@updateNotice')->name('information.notice');
        /* Information text -- END*/



        Route::resource('tech-support-msg', 'TechMsgController');
        Route::resource('chef', 'ChefController');
        Route::resource('operator', 'OperatorController');
        Route::resource('ball-technician', 'BallTechnicianController');
        Route::resource('admin', 'AdminController');
        Route::resource('user', 'UserController'); //todo: not sure that there is some standard methods


        Route::get('/access-structure/abilities', 'StaffAccessStructure\AbilityController@abilities')->name('access-structure.abilities');
        Route::get('/access-structure/assigned-roles', 'StaffAccessStructure\AssignedRoleController@assignedRoles')->name('access-structure.assigned-roles');
        Route::get('/access-structure/permissions', 'StaffAccessStructure\PermissionController@permissions')->name('access-structure.permissions');
        Route::get('/access-structure/roles', 'StaffAccessStructure\RoleController@roles')->name('access-structure.roles');



//        Route::get('/matrix', 'MatrixController@index')->name('matrix-index');

    });











//consider to place all this route to admin-panel prefix, after you refactor them
//    similar routes have they representations undex matrix prefix, deal with them, which one of them are actual

    Route::post('/user/save-operator-to-session', 'OperatorController@saveOperatorToSession');
    // Not used routes------------------------------------------------------------------------------------
    Route::get('/user/{user}', 'UserController@showUserProfile');

    Route::get('matrix/grab-messages', 'MatrixController@getStudioMessagesFromMatrixChat');
    Route::get('matrix/send-message', 'MatrixController@sendMessageToChat');

    Route::post('matrix/chat', 'MatrixController@sendMessageToChat')->name('matrix.chat.send');
    Route::get('matrix/ajax', 'MatrixController@talkToAjax');
    Route::get('matrix/get-messages', 'MatrixController@getMessages');

    Route::get('/admin_panel/matrix', 'MatrixController@index');
    //@todo: consider to remove
    Route::post('matrix/send', 'MatrixController@sendMessage')->name('matrix.send'); //journal.blade.php dependant route. Called when tech.sup. msg. send






    Route::get('/text/tech-instruction', 'InformationController@techInstruction');



});

app/Information.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Information extends Model
{
    //
}

app/Http/Controllers/InformationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Information;

class InformationController extends Controller
{
    public function techInstruction()
    {
        return view('admin_panel_view.information.tech-instruction');
    }


    public function instruction()
    {
        $instruction = Information::where('name', 'instruction')->first();
        return view('admin_panel_view.information.instruction', compact('instruction'));
    }

    public function updateInstruction(Request $request)
    {
        $this->validate(request(), [
            'content' => 'required|string'
        ]);

        Information::where('name', 'instruction')->update([
            'content' => $request->get('content')
        ]);
        \Cache::forget('journalViewData.information');

        return back()->withErrors(['Изменения сохранены']);
    }


    public function notification()
    {
        $notification = Information::where('name', 'notification')->first();
        return view('admin_panel_view.information.notification', compact('notification'));
    }


    public function updateNotification(Request $request)
    {
        $this->validate(request(), [
            'content' => 'string',
            'expiration' => 'date'
        ]);

        Information::where('name', 'notification')->update([
            'content' => $request->get('content'),
            'expiration' => $request->expiration
        ]);
        \Cache::forget('journalViewData.information');

        return back()->withErrors(['Изменения сохранены']);
    }


    public function notice()
    {
        $notice = Information::where('name', 'notice')->first();
        return view('admin_panel_view.information.notice', compact('notice'));
    }


    public function updateNotice(Request $request)
    {
        $this->validate(request(), [
            'content' => 'string'
        ]);

        Information::where('name', 'notice')->update([
            'content' => $request->get('content')
        ]);
        \Cache::forget('journalViewData.information');

        return back()->withErrors(['Изменения сохранены']);
    }
}

resources/views/admin_panel_view/information/instruction.blade.php
@extends('admin_panel_view.layout.master')
@section('content')

    <script src="{{asset('/js/page_text_editor.js')}}" type="text/javascript" ></script>
    <script type="text/javascript">
        bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
    </script>

    <header id="page-header">
        <h1>Инструкция к элетронному журналу</h1>   <!-- page title -->
    </header>

    <div id="content" class="padding-20">  <!-- all content wrapper-->

        @include('general_view.errors.post_errors_success')

        <div id="panel-5" class="panel panel-default">  <!--  all content div -->
            <div class="panel-heading">
                <span class="title elipsis">
                    <strong>Редактировать</strong> <!-- panel title -->
                </span>
                <!-- right options -->
                <ul class="options pull-right list-inline">
                    <li><a href="#" class="opt panel_colapse" data-toggle="tooltip" title="Colapse" data-placement="bottom"></a></li>
                    <li><a href="#" class="opt panel_fullscreen hidden-xs" data-toggle="tooltip" title="Fullscreen" data-placement="bottom"><i class="fa fa-expand"></i></a></li>
                    <li><a href="#" class="opt panel_close" data-confirm-title="Confirm" data-confirm-message="Are you sure you want to remove this panel?" data-toggle="tooltip" title="Close" data-placement="bottom"><i class="fa fa-times"></i></a></li>
                </ul>
            </div>


            <div class="panel-body">    <!-- panel content -->
                <div class="table-responsive">
                    <form action="{{route('admin-panel.information.instruction')}}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('patch') }}
                    <textarea name="content" style="width: 100%;">{{$instruction->content}}</textarea>
                    <button type="submit" class="btn btn-light btn-outline-secondary mt-4"><i class="fa fa-save white"></i> Сохранить </button>

                    </form>
                </div>
            </div>     <!-- /panel content -->
        </div>
    </div>



@endsection

resources/views/admin_panel_view/information/notice.blade.php
@extends('admin_panel_view.layout.master')
@section('content')
    <script src="{{asset('/js/page_text_editor.js')}}" type="text/javascript" ></script>

   <script type="text/javascript">
        bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
    </script>

    <header id="page-header">
        <h1>Информация для студийных операторов</h1>   <!-- page title -->
    </header>

    <div id="content" class="padding-20">  <!-- all content wrapper-->

        @include('general_view.errors.post_errors_success')

        <div id="panel-5" class="panel panel-default">  <!--  all content div -->
            <div class="panel-heading">
                <span class="title elipsis">
                    <strong>Редактировать</strong> <!-- panel title -->
                </span>
            </div>


            <div class="panel-body">    <!-- panel content -->
                <div class="table-responsive">
                    <form action="{{route('admin-panel.information.notice')}}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('patch') }}
                        <textarea name="content" style="width: 100%;">{{$notice->content}}</textarea>
                        <button type="submit" class="btn btn-light btn-outline-secondary mt-4"><i class="fa fa-save white"></i> Сохранить </button>
                    </form>
                </div>
            </div>     <!-- /panel content -->
        </div>
    </div>



@endsection

resources/views/admin_panel_view/information/notification.blade.php
@extends('admin_panel_view.layout.master')
@section('content')
    <script src="{{asset('/js/page_text_editor.js')}}" type="text/javascript" ></script>

    <script type="text/javascript">
        bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
    </script>

    <header id="page-header">
        <h1>Объявление для студийных операторов</h1>   <!-- page title -->
    </header>

    <div id="content" class="padding-20">  <!-- all content wrapper-->

        @include('general_view.errors.post_errors_success')

        <div id="panel-5" class="panel panel-default">  <!--  all content div -->
            <div class="panel-heading">
                <span class="title elipsis">
                    <strong>Редактировать</strong> <!-- panel title -->
                </span>
            </div>


            <div class="panel-body">    <!-- panel content -->
                <div class="table-responsive">
                    <form action="{{route('admin-panel.information.notification')}}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('patch') }}
                        <label for="expirationDatePicker">Введите дату истечения актуальности объявления:</label>
                        <input type="date" name="expiration" id="expirationDatePicker">
                        <textarea name="content" style="width: 100%;">{{$notification->content}}</textarea>
                        <button type="submit" class="btn btn-light btn-outline-secondary mt-4"><i class="fa fa-save white"></i> Сохранить </button>
                    </form>
                </div>
            </div>     <!-- /panel content -->
        </div>
    </div>
@endsection

resources/views/admin_panel_view/information/tech-instruction.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>AlphaMedia journal</title>

    <meta http-equiv="refresh" content="7200" >
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

<style>
    html{
        height:98%;
        width:98%;
    }

    body, #iframeForDock{
        height:100%;
        width:100%;
    }
    </style>

</head>
<body>

    <iframe id="iframeForDock" src="https://docs.google.com/document/d/127_kYXsnGXa8HRMpNqW7zgbu6Pxn9U_mrF9XeEMYDXQ/edit?usp=sharing" ></iframe>

</body>
</html>

resources/views/admin_panel_view/information/tech_msg.blade.php
@extends('admin_panel_view.layout.master')
@section('content')

    <header id="page-header">
        <h1>Сообщения для технической поддержки</h1>   <!-- page title -->
    </header>

    <div id="content" class="padding-20">  <!-- all content wrapper-->

    @include('general_view.errors.post_errors')

    @foreach($studios as $studio)   <!-- looping through all studios -->

        <div id="panel-5" class="panel panel-default">  <!--  all content div -->
            <div class="panel-heading">
                <span class="title elipsis">
                    <strong>{{$studio->name_ru}}</strong> <!-- panel title -->
                </span>
            </div>

            <div class="panel-body">    <!-- panel content -->
                <div class="table-responsive">
                    <table class="table table-sm table-striped mt-4">
                        <thead>
                        <tr>
                            <th>___ID___</th>
                            <th>Приоритет</th>
                            <th>Название на ENG</th>
                            <th>Название на RU</th>
                            <th>ID описания</th>
                            <th>Изменить</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($techMsg as $msg)
                            @if($studio->id == $msg->studio_id )
                                <tr>
                                    <td class="tech_message_id" data-msg-id="{{$msg->id}}" data-msg-studio-id="{{$studio->id}}">{{$msg->id}}</td>
                                    <td class="tech_message_order"  data-msg-id="{{$msg->id}}" data-msg-studio-id="{{$studio->id}}">{{$msg->order}}</td>
                                    <td class="tech_message_name_ru"  data-msg-id="{{$msg->id}}" data-msg-studio-id="{{$studio->id}}">{{$msg->tech_msg_name_eng}}</td>
                                    <td class="tech_message_name_eng"  data-msg-id="{{$msg->id}}" data-msg-studio-id="{{$studio->id}}">{{$msg->tech_msg_name_ru}}</td>
                                    <td class="tech_message_corresponding_description"  data-msg-id="{{$msg->id}}" data-msg-studio-id="{{$studio->id}}"><?php if (isset($msg->description)){echo $msg->description->text;}?></td>
                                    <td>   <!-- edit button-->
                                        <a class="btn btn-light btn-outline-secondary btn-sm"
                                           data-msg-id="{{$msg->id}}"
                                           data-msg-studio-id="{{$studio->id}}"
                                           href="javascript:;"
                                           onclick="editFormDisplay(this);">
                                            <i class="fa fa-edit white"></i>
                                            Edit
                                        </a>
                                    </td>
                                    <td>  <!-- delete button-->
                                        <a class="btn btn-light btn-outline-secondary btn-sm"
                                           data-msg-id="{{$msg->id}}"
                                           data-msg-studio-id="{{$studio->id}}"
                                           href="javascript:;"
                                           onclick="deleteFormSubmit(this);">
                                            <i class="fa fa-times white"></i>
                                            Delete
                                        </a>
                                    </td>
                                </tr>
                            @endif
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>     <!-- /panel content -->

            <div class="panel-footer">    <!-- panel footer -->

                <div class="text-left">    <!-- pre code -->
                    <a class="btn btn-xs btn-info mt-4 mb-4"
                       href="javascript:;"
                       onclick="jQuery('#pre-{{$studio->name_eng}}').slideToggle();">
                        Добавить Сообщение
                    </a>
                </div>

                <div id="pre-{{$studio->name_eng}}" class="text-left noradius text-danger softhide">
                    <form class="" action="/admin/tech-support" method="post" enctype="multipart/form-data" data-success="Sent! Thank you!" data-toastr-position="top-right">
                        {{ csrf_field() }}
                        <fieldset>

                            <div class="row form-group">
                                <label class="col-md-3 col-sm-3">Приоритет </label>
                                <input type="number" min="0" name="order" value="" class="form-control col-md col-sm required">
                            </div>


                            <div class="row form-group">
                                <label class="col-md-3 col-sm-3">Соответствующие описание </label>
                                <select name="description_id" class="form-control col-md col-sm pointer required">
                                    <option value="2" selected="selected">--- Выберите ---</option>
                                        @foreach($descriptions as $description){
                                            @if ($description->studio_id == $studio->id)
                                                <option value="{{$description->id}}">{{$description->text}}</option>
                                            @endif
                                        @endforeach
                                </select>
                            </div>

                            <div class="row form-group">
                                <label class="col-md-3 col-sm-3">Текст на английском</label>
                                <input name="name_eng" value="" class="form-control col-md col-sm required">
                                <input type="hidden" name="studio_id" value="{{$studio->id}}">
                            </div>

                            <div class="row form-group">
                                <label class="col-md-3 col-sm-3">Текст на русском</label>
                                <input name="name_ru" value="" class="form-control col-md col-sm required">
                            </div>


                            <div class="row form-group">
                                <div class="col-md-3 col-sm-3"></div>
                                <div class="col-md col-sm">
                                    <button type="submit" class="btn btn-light btn-outline-secondary"><i class="fa fa-save white"></i> Сохранить </button>
                                </div>
                            </div>

                        </fieldset>
                    </form>
                </div>

                <div id="edit-{{$studio->id}}" class="text-left noradius text-danger softhide">

                    <form class="" action="" method="post">
                        {{ csrf_field() }}
                        {{ method_field('patch') }}

                        <fieldset>
                            <input type="hidden" name="_method" value="patch">

                            <div class="row form-group">
                                <label class="col-md-3 col-sm-3">Приоритет</label>
                                <input type="number" min="0" id="form-edit-order-{{$studio->id}}" name="order" value="" class="form-control col-md col-sm">
                            </div>

                            <div class="row form-group">
                                <label class="col-md-3 col-sm-3">Соответствующие описание</label>
                                <select name="description_id" class="form-control col-md col-sm pointer required">
                                    <option value="2" selected="selected">--- Выберите ---</option>
                                        @foreach($descriptions as $description){
                                            @if ($description->studio_id == $studio->id)
                                                <option value="{{$description->id}}">{{$description->text}}</option>
                                            @endif
                                        @endforeach
                                </select>
                            </div>

                            <div class="row form-group">
                                <label class="col-md-3 col-sm-3">Текст на английском</label>
                                <input type="text" id="form-edit-name-eng-{{$studio->id}}" name="name_eng" value="" class="form-control col-md col-sm required">
                                <input type="hidden" name="studio_id" value="{{$studio->id}}">
                            </div>

                            <div class="row form-group">
                                <label class="col-md-3 col-sm-3">Текст на русском</label>
                                <input type="text" id="form-edit-name-ru-{{$studio->id}}" name="name_ru" value="" class="form-control col-md col-sm required">
                            </div>

                            <div class="row form-group">
                                <div class="col-md-3 col-sm-3"></div>
                                <div class="col-md col-sm">
                                    <button type="submit" class="btn btn-light btn-outline-secondary"><i class="fa fa-save white"></i> Сохранить </button>
                                </div>
                            </div>

                        </fieldset>
                    </form>




                </div>  <!-- /pre code -->
            </div>    <!-- /panel footer -->
        </div>
        @endforeach
    </div>

    <div id="delete-texh-msg" class="text-left noradius text-danger softhide">
        <form action="" method="post">
            {{ csrf_field() }}
            {{ method_field('delete') }}
            <input type="hidden" name="delete-description-id" id="deleteDescriptionId" >
        </form>
    </div>




    <script src="{{asset('admin_panel/js/technical_messages_for_support/master.js')}}"  type="text/javascript"></script>
@endsection